from rest_framework import serializers

from core.media import signed_media_url

from .models import MRIAnalysis


class MRIAnalysisSerializer(serializers.ModelSerializer):
    """Read serializer for MRI analyses.

    Exposes computed *_url fields that build absolute URLs from the file
    field (uploaded original) and the stored result paths (mask/overlay/
    analysis figures generated by the inference pipeline).
    """

    file_url = serializers.SerializerMethodField()
    mask_url = serializers.SerializerMethodField()
    overlay_url = serializers.SerializerMethodField()
    analysis_url = serializers.SerializerMethodField()

    class Meta:
        model = MRIAnalysis
        fields = (
            'id',
            'patient',
            'file',
            'file_url',
            'status',
            'model_used',
            'result_tumor_detected',
            'result_tumor_type',
            'result_confidence',
            'result_mask_path',
            'result_overlay_path',
            'result_analysis_path',
            'mask_url',
            'overlay_url',
            'analysis_url',
            'result_report',
            'created_at',
        )
        read_only_fields = (
            'id', 'status', 'model_used',
            'result_tumor_detected', 'result_tumor_type', 'result_confidence',
            'result_mask_path', 'result_overlay_path', 'result_analysis_path',
            'result_report', 'created_at',
            'file_url', 'mask_url', 'overlay_url', 'analysis_url',
        )

    # ---- url helpers (signed, time-limited — see core.media) -----------

    def get_file_url(self, obj):
        if not obj.file:
            return None
        return signed_media_url(self.context.get('request'), obj.file.url)

    def get_mask_url(self, obj):
        return signed_media_url(self.context.get('request'), obj.result_mask_path)

    def get_overlay_url(self, obj):
        return signed_media_url(self.context.get('request'), obj.result_overlay_path)

    def get_analysis_url(self, obj):
        return signed_media_url(self.context.get('request'), obj.result_analysis_path)
