# Generated by Django 3.2.25 on 2026-05-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrianalysis',
            name='result_analysis_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mrianalysis',
            name='result_overlay_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mrianalysis',
            name='file',
            field=models.FileField(upload_to='mri/uploads/'),
        ),
    ]
