# Generated by Django 3.2.25 on 2026-05-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECGAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ecg/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('model_used', models.CharField(blank=True, max_length=255)),
                ('result_arrhythmia_detected', models.BooleanField(blank=True, null=True)),
                ('result_arrhythmia_type', models.CharField(blank=True, max_length=255, null=True)),
                ('result_confidence', models.FloatField(blank=True, null=True)),
                ('result_hrv_metrics', models.JSONField(blank=True, null=True)),
                ('result_report', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecg_analyses', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'ECG analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
