# Generated by Django 3.2.25 on 2026-05-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecganalysis',
            name='result_pathology_probabilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecganalysis',
            name='result_plot_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ecganalysis',
            name='file',
            field=models.FileField(upload_to='ecg/uploads/'),
        ),
    ]
